version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306"

  springboot-app:
    # Cambio: Usamos "." porque el Dockerfile está en la misma carpeta que este archivo
    build: .
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql